// Code generated from the original single-file app's built-in trivia set; do not hand-edit.
// Ported verbatim from the ~500-question QUESTIONS array in the pre-rewrite index.html.
package questionbank

import "weakestlink/internal/room"

// SeedQuestions is inserted into the questions table on first boot only,
// so a fresh deployment never starts with an empty community bank.
var SeedQuestions = []room.Question{
	{Q: "What is the capital of France?", A: "Paris"},
	{Q: "What is the capital of Japan?", A: "Tokyo"},
	{Q: "What is the capital of Canada?", A: "Ottawa"},
	{Q: "What is the capital of Australia?", A: "Canberra"},
	{Q: "What is the capital of Egypt?", A: "Cairo"},
	{Q: "What is the capital of Italy?", A: "Rome"},
	{Q: "What is the capital of Germany?", A: "Berlin"},
	{Q: "What is the capital of Spain?", A: "Madrid"},
	{Q: "What is the capital of Russia?", A: "Moscow"},
	{Q: "What is the capital of China?", A: "Beijing"},
	{Q: "What is the capital of India?", A: "New Delhi"},
	{Q: "What is the capital of Brazil?", A: "Brasília"},
	{Q: "What is the capital of Mexico?", A: "Mexico City"},
	{Q: "What is the capital of South Korea?", A: "Seoul"},
	{Q: "What is the capital of the United Kingdom?", A: "London"},
	{Q: "What is the capital of Greece?", A: "Athens"},
	{Q: "What is the capital of Turkey?", A: "Ankara"},
	{Q: "What is the capital of Thailand?", A: "Bangkok"},
	{Q: "What is the capital of Argentina?", A: "Buenos Aires"},
	{Q: "What is the capital of Kenya?", A: "Nairobi"},
	{Q: "What is the capital of Sweden?", A: "Stockholm"},
	{Q: "What is the capital of Norway?", A: "Oslo"},
	{Q: "What is the capital of Portugal?", A: "Lisbon"},
	{Q: "What is the capital of the Netherlands?", A: "Amsterdam"},
	{Q: "What is the capital of Switzerland?", A: "Bern"},
	{Q: "What is the capital of Austria?", A: "Vienna"},
	{Q: "What is the capital of Poland?", A: "Warsaw"},
	{Q: "What is the capital of Ireland?", A: "Dublin"},
	{Q: "What is the capital of Cuba?", A: "Havana"},
	{Q: "What is the capital of Indonesia?", A: "Jakarta"},
	{Q: "What is the largest country in the world by area?", A: "Russia"},
	{Q: "What is the smallest country in the world?", A: "Vatican City"},
	{Q: "What is the longest river in the world?", A: "The Nile"},
	{Q: "What is the largest ocean on Earth?", A: "The Pacific Ocean"},
	{Q: "What is the largest hot desert in the world?", A: "The Sahara"},
	{Q: "What is the tallest mountain in the world?", A: "Mount Everest"},
	{Q: "Which continent is the Sahara Desert located on?", A: "Africa"},
	{Q: "Which continent has the most countries?", A: "Africa"},
	{Q: "What is the smallest continent by land area?", A: "Australia"},
	{Q: "What is the largest continent by area?", A: "Asia"},
	{Q: "What ocean lies between Africa and the Americas?", A: "The Atlantic Ocean"},
	{Q: "What is the longest wall ever built, located in China?", A: "The Great Wall of China"},
	{Q: "Which country has the most natural lakes?", A: "Canada"},
	{Q: "What is the driest continent on Earth?", A: "Antarctica"},
	{Q: "Which country is considered transcontinental, in both Europe and Asia?", A: "Turkey"},
	{Q: "What is the capital of the United States?", A: "Washington, D.C."},
	{Q: "What is the most populous country in the world?", A: "India"},
	{Q: "Which US state is the largest by area?", A: "Alaska"},
	{Q: "Which US state is the smallest by area?", A: "Rhode Island"},
	{Q: "What is the tallest waterfall in the world?", A: "Angel Falls"},
	{Q: "Which country is home to the Great Barrier Reef?", A: "Australia"},
	{Q: "What is the name of the strait separating Europe and Africa near Spain?", A: "The Strait of Gibraltar"},
	{Q: "Which South American country is named after a famous explorer?", A: "Colombia"},
	{Q: "What is the highest capital city in the world?", A: "La Paz, Bolivia"},
	{Q: "What is the currency of Japan?", A: "The yen"},
	{Q: "What is the currency of the United Kingdom?", A: "The pound sterling"},
	{Q: "What is the currency used by most of the European Union?", A: "The euro"},
	{Q: "Which African country was formerly known as Abyssinia?", A: "Ethiopia"},
	{Q: "What is the name of the mountain range that runs through South America?", A: "The Andes"},
	{Q: "What is the name of the largest rainforest in the world?", A: "The Amazon rainforest"},
	{Q: "Which continent lies entirely within the Southern Hemisphere and is also a country?", A: "Australia"},
	{Q: "What is the capital of New Zealand?", A: "Wellington"},
	{Q: "Which country has the most time zones?", A: "France"},
	{Q: "What is the northernmost capital city in the world?", A: "Reykjavik"},
	{Q: "Which sea separates Saudi Arabia from Egypt?", A: "The Red Sea"},
	{Q: "What is the name of the canal that connects the Mediterranean Sea and the Red Sea?", A: "The Suez Canal"},
	{Q: "What is the name of the canal that connects the Atlantic and Pacific Oceans through Central America?", A: "The Panama Canal"},
	{Q: "Which country is famous for its canals and windmills?", A: "The Netherlands"},
	{Q: "What island country lies just south of India?", A: "Sri Lanka"},
	{Q: "Which desert covers much of northern China and Mongolia?", A: "The Gobi Desert"},
	{Q: "What planet is known as the Red Planet?", A: "Mars"},
	{Q: "What gas do plants absorb from the atmosphere for photosynthesis?", A: "Carbon dioxide"},
	{Q: "What is the chemical symbol for gold?", A: "Au"},
	{Q: "What is the chemical symbol for water?", A: "H2O"},
	{Q: "What is the freezing point of water in Celsius?", A: "Zero degrees"},
	{Q: "What is the boiling point of water in Celsius at sea level?", A: "100 degrees"},
	{Q: "What is the powerhouse of the cell called?", A: "The mitochondria"},
	{Q: "What force pulls objects toward the Earth?", A: "Gravity"},
	{Q: "What is the hardest natural substance on Earth?", A: "Diamond"},
	{Q: "What metal is liquid at room temperature?", A: "Mercury"},
	{Q: "What is the largest organ in the human body?", A: "The skin"},
	{Q: "How many bones are in the adult human body?", A: "206"},
	{Q: "What is the main gas found in the air we breathe?", A: "Nitrogen"},
	{Q: "What organ pumps blood through the human body?", A: "The heart"},
	{Q: "What is the study of earthquakes called?", A: "Seismology"},
	{Q: "What is the study of weather called?", A: "Meteorology"},
	{Q: "What part of the plant conducts photosynthesis?", A: "The leaves"},
	{Q: "What is the smallest unit of life?", A: "The cell"},
	{Q: "What gas do humans and animals need to breathe to survive?", A: "Oxygen"},
	{Q: "What is the process by which plants make their food called?", A: "Photosynthesis"},
	{Q: "What is the chemical symbol for sodium?", A: "Na"},
	{Q: "What is the chemical symbol for iron?", A: "Fe"},
	{Q: "What natural phenomenon is measured using the Richter scale?", A: "Earthquakes"},
	{Q: "What type of energy is stored in a battery called?", A: "Chemical energy"},
	{Q: "What blood type is known as the universal donor?", A: "O negative"},
	{Q: "What is the largest bone in the human body?", A: "The femur"},
	{Q: "What is the smallest bone in the human body?", A: "The stapes"},
	{Q: "How many chambers does the human heart have?", A: "Four"},
	{Q: "What vitamin does the body produce when exposed to sunlight?", A: "Vitamin D"},
	{Q: "What is the pH value of pure water?", A: "Seven"},
	{Q: "What is the term for an animal that eats only plants?", A: "Herbivore"},
	{Q: "What is the term for an animal that eats only meat?", A: "Carnivore"},
	{Q: "What is the term for an animal that eats both plants and meat?", A: "Omnivore"},
	{Q: "What natural satellite orbits the Earth?", A: "The Moon"},
	{Q: "What causes the tides in Earth's oceans?", A: "The gravitational pull of the Moon"},
	{Q: "What is the study of living organisms called?", A: "Biology"},
	{Q: "What is the study of matter and energy called?", A: "Physics"},
	{Q: "What is the study of chemicals and their reactions called?", A: "Chemistry"},
	{Q: "What is the closest star to Earth?", A: "The Sun"},
	{Q: "What is the term for water changing directly from a solid to a gas?", A: "Sublimation"},
	{Q: "What is the chemical formula for table salt?", A: "NaCl"},
	{Q: "What part of the body is affected by asthma?", A: "The lungs"},
	{Q: "What gas makes up most of the Earth's atmosphere?", A: "Nitrogen"},
	{Q: "What is the name of the layer of gases surrounding Earth?", A: "The atmosphere"},
	{Q: "What natural disaster is measured in categories from 1 to 5?", A: "A hurricane"},
	{Q: "What is the term for the variety of life in the world or a habitat?", A: "Biodiversity"},
	{Q: "What is the process of a caterpillar becoming a butterfly called?", A: "Metamorphosis"},
	{Q: "Besides support, what is a main function of the human skeleton?", A: "Protecting internal organs"},
	{Q: "What is the largest gland in the human body?", A: "The liver"},
	{Q: "What element does the symbol O represent?", A: "Oxygen"},
	{Q: "What element does the symbol C represent?", A: "Carbon"},
	{Q: "What is the approximate speed of light in a vacuum?", A: "About 300,000 kilometers per second"},
	{Q: "Who developed the theory of evolution by natural selection?", A: "Charles Darwin"},
	{Q: "Who developed the theory of relativity?", A: "Albert Einstein"},
	{Q: "Who is credited with discovering gravity after seeing a falling apple?", A: "Isaac Newton"},
	{Q: "Which scientist is known for research on radioactivity and won two Nobel Prizes?", A: "Marie Curie"},
	{Q: "What is DNA short for?", A: "Deoxyribonucleic acid"},
	{Q: "What is the basic unit of heredity called?", A: "A gene"},
	{Q: "What is the term for the force that opposes motion between two surfaces?", A: "Friction"},
	{Q: "What state of matter has no fixed shape or volume?", A: "Gas"},
	{Q: "What state of matter has a fixed volume but no fixed shape?", A: "Liquid"},
	{Q: "What is the center of an atom called?", A: "The nucleus"},
	{Q: "What are the tiny particles that orbit the nucleus of an atom called?", A: "Electrons"},
	{Q: "What is the study of the stars and outer space called?", A: "Astronomy"},
	{Q: "What is the term for a substance that speeds up a chemical reaction without being consumed?", A: "A catalyst"},
	{Q: "What natural process turns water vapor into clouds?", A: "Condensation"},
	{Q: "What is the main function of red blood cells?", A: "To carry oxygen through the body"},
	{Q: "What sense organ is responsible for detecting light?", A: "The eye"},
	{Q: "What is the average human body temperature in Celsius?", A: "37 degrees"},
	{Q: "What is the term for animals that are active mainly at night?", A: "Nocturnal"},
	{Q: "What year did World War II end?", A: "1945"},
	{Q: "What year did World War I begin?", A: "1914"},
	{Q: "Who was the first President of the United States?", A: "George Washington"},
	{Q: "In what year did the Titanic sink?", A: "1912"},
	{Q: "Which country gifted the Statue of Liberty to the United States?", A: "France"},
	{Q: "Who was the British Prime Minister during most of World War II?", A: "Winston Churchill"},
	{Q: "What ancient civilization built the pyramids of Giza?", A: "The ancient Egyptians"},
	{Q: "What wall divided East and West Berlin during the Cold War?", A: "The Berlin Wall"},
	{Q: "In what year did the Berlin Wall fall?", A: "1989"},
	{Q: "Who was the first man to walk on the Moon?", A: "Neil Armstrong"},
	{Q: "In what year did the first Moon landing happen?", A: "1969"},
	{Q: "What ship did the Pilgrims sail to America on in 1620?", A: "The Mayflower"},
	{Q: "Who was the ancient Egyptian queen famous for her relationships with Julius Caesar and Mark Antony?", A: "Cleopatra"},
	{Q: "What empire was ruled by Julius Caesar?", A: "The Roman Empire"},
	{Q: "Who painted the ceiling of the Sistine Chapel?", A: "Michelangelo"},
	{Q: "What document, signed in 1215, limited the power of the English king?", A: "The Magna Carta"},
	{Q: "Who was the leader of Nazi Germany during World War II?", A: "Adolf Hitler"},
	{Q: "What year did the United States declare independence?", A: "1776"},
	{Q: "Who wrote the Declaration of Independence?", A: "Thomas Jefferson"},
	{Q: "What war was fought between the American North and South from 1861 to 1865?", A: "The American Civil War"},
	{Q: "Who was the 16th President of the United States, who led the country through the Civil War?", A: "Abraham Lincoln"},
	{Q: "What ancient wonder of the world was located in Alexandria, Egypt?", A: "The Lighthouse of Alexandria"},
	{Q: "Which explorer is credited with reaching the Americas in 1492?", A: "Christopher Columbus"},
	{Q: "What was the name of the period of rebuilding art and learning in Europe from the 14th to 17th century?", A: "The Renaissance"},
	{Q: "Who was the Queen of England during much of the 19th century, giving her name to an era?", A: "Queen Victoria"},
	{Q: "What was the name of the ship that Charles Darwin sailed on during his famous voyage?", A: "HMS Beagle"},
	{Q: "What country was ruled by pharaohs?", A: "Ancient Egypt"},
	{Q: "Who was the first Emperor of Rome?", A: "Augustus"},
	{Q: "What was the name of the global pandemic that occurred from 1918 to 1919?", A: "The Spanish Flu"},
	{Q: "In what year did India gain independence from Britain?", A: "1947"},
	{Q: "Who was the South African leader who fought against apartheid and became president in 1994?", A: "Nelson Mandela"},
	{Q: "What was the name of the Cold War rival to the United States?", A: "The Soviet Union"},
	{Q: "Who was the first person to fly solo across the Atlantic Ocean?", A: "Charles Lindbergh"},
	{Q: "What treaty officially ended World War I?", A: "The Treaty of Versailles"},
	{Q: "What ancient Greek city-state is considered the birthplace of democracy?", A: "Athens"},
	{Q: "Who was the Macedonian king who built one of the largest empires of the ancient world?", A: "Alexander the Great"},
	{Q: "What was the name of the wall built by the Romans in northern England?", A: "Hadrian's Wall"},
	{Q: "In which country did the French Revolution take place?", A: "France"},
	{Q: "What year did the French Revolution begin?", A: "1789"},
	{Q: "Who was the French military leader who became Emperor in the early 1800s?", A: "Napoleon Bonaparte"},
	{Q: "What was the name of the era of strict racial segregation in South Africa?", A: "Apartheid"},
	{Q: "Who was assassinated in Sarajevo in 1914, an event that helped trigger World War I?", A: "Archduke Franz Ferdinand"},
	{Q: "What was the name of the airlift that supplied West Berlin in 1948-1949?", A: "The Berlin Airlift"},
	{Q: "What year did the Wright brothers achieve the first powered flight?", A: "1903"},
	{Q: "Who was the first woman to fly solo across the Atlantic Ocean?", A: "Amelia Earhart"},
	{Q: "What was the name of the great fire that destroyed much of London in 1666?", A: "The Great Fire of London"},
	{Q: "Who was the King of England who had six wives?", A: "Henry VIII"},
	{Q: "What was the name of the ancient library famous for its vast collection of scrolls, located in Egypt?", A: "The Library of Alexandria"},
	{Q: "What was the capital of the Byzantine Empire?", A: "Constantinople"},
	{Q: "What is Constantinople known as today?", A: "Istanbul"},
	{Q: "What was the name of the trade route connecting China and the Mediterranean?", A: "The Silk Road"},
	{Q: "Who led the Cuban Revolution and later became Cuba's leader?", A: "Fidel Castro"},
	{Q: "What approach did Mahatma Gandhi's independence movement in India rely on?", A: "Nonviolent resistance"},
	{Q: "What year did the Soviet Union collapse?", A: "1991"},
	{Q: "Who was assassinated in 1963 while serving as US President?", A: "John F. Kennedy"},
	{Q: "What was the name of the 1969 music festival held in upstate New York?", A: "Woodstock"},
	{Q: "Who was the civil rights leader who delivered the 'I Have a Dream' speech?", A: "Martin Luther King Jr."},
	{Q: "What year did apartheid officially end in South Africa?", A: "1994"},
	{Q: "What war was fought in Vietnam with heavy US involvement during the 1960s and 70s?", A: "The Vietnam War"},
	{Q: "What year was the United States Constitution ratified?", A: "1788"},
	{Q: "Who wrote the play Romeo and Juliet?", A: "William Shakespeare"},
	{Q: "Who painted the Mona Lisa?", A: "Leonardo da Vinci"},
	{Q: "What instrument has 88 keys?", A: "The piano"},
	{Q: "How many strings does a standard violin have?", A: "Four"},
	{Q: "Who wrote the Harry Potter book series?", A: "J.K. Rowling"},
	{Q: "What is the name of the wizarding school in Harry Potter?", A: "Hogwarts"},
	{Q: "Who directed the movies Jaws and E.T.?", A: "Steven Spielberg"},
	{Q: "What is the name of the famous clock tower in London?", A: "Big Ben"},
	{Q: "Who composed the Ninth Symphony despite being deaf?", A: "Ludwig van Beethoven"},
	{Q: "What art movement is Salvador Dalí associated with?", A: "Surrealism"},
	{Q: "Who wrote the novel Pride and Prejudice?", A: "Jane Austen"},
	{Q: "Who wrote the novel Moby-Dick?", A: "Herman Melville"},
	{Q: "What is the name of the boy wizard in J.K. Rowling's book series?", A: "Harry Potter"},
	{Q: "Who painted Starry Night?", A: "Vincent van Gogh"},
	{Q: "What Italian artist sculpted the statue of David?", A: "Michelangelo"},
	{Q: "What is the best-selling video game series featuring a plumber?", A: "Super Mario"},
	{Q: "Who created the fictional detective Sherlock Holmes?", A: "Arthur Conan Doyle"},
	{Q: "What Disney movie features a snowman named Olaf?", A: "Frozen"},
	{Q: "What is the name of the fictional continent in The Lord of the Rings?", A: "Middle-earth"},
	{Q: "Who wrote The Lord of the Rings?", A: "J.R.R. Tolkien"},
	{Q: "What museum in Paris houses the Mona Lisa?", A: "The Louvre"},
	{Q: "What opera house is famous for its sail-shaped roof in Sydney?", A: "The Sydney Opera House"},
	{Q: "Who directed the original Star Wars trilogy?", A: "George Lucas"},
	{Q: "What is the name of the fictional British spy created by Ian Fleming?", A: "James Bond"},
	{Q: "What is the name of the film franchise centered on Marvel superheroes?", A: "The Marvel Cinematic Universe"},
	{Q: "Who composed The Four Seasons?", A: "Antonio Vivaldi"},
	{Q: "What is the name of the coffee shop featured in the sitcom Friends?", A: "Central Perk"},
	{Q: "Who wrote the dystopian novel 1984?", A: "George Orwell"},
	{Q: "Who wrote the novel To Kill a Mockingbird?", A: "Harper Lee"},
	{Q: "What is the term for a 14-line poem, often about love?", A: "A sonnet"},
	{Q: "Who is known as the King of Pop?", A: "Michael Jackson"},
	{Q: "Who is known as the Queen of Pop?", A: "Madonna"},
	{Q: "What band did John Lennon and Paul McCartney belong to?", A: "The Beatles"},
	{Q: "What city is considered the birthplace of jazz music?", A: "New Orleans"},
	{Q: "What is the name of the fictional wizard who mentors Harry Potter?", A: "Albus Dumbledore"},
	{Q: "What fairy tale character pricks her finger and falls asleep for 100 years?", A: "Sleeping Beauty"},
	{Q: "Who wrote well-known French versions of fairy tales like Cinderella and Sleeping Beauty?", A: "Charles Perrault"},
	{Q: "What is the term for a piece of music written for a solo instrument and orchestra?", A: "A concerto"},
	{Q: "What Renaissance artist is known for painting The Last Supper?", A: "Leonardo da Vinci"},
	{Q: "What is the name of the theater company associated with William Shakespeare in London?", A: "The Globe Theatre"},
	{Q: "Who composed the opera The Marriage of Figaro?", A: "Wolfgang Amadeus Mozart"},
	{Q: "What is the name of the famous art museum in New York City known by the initials MET?", A: "The Metropolitan Museum of Art"},
	{Q: "What long-running animated sitcom is set in the fictional town of Springfield?", A: "The Simpsons"},
	{Q: "What is the highest award given in the film industry, presented annually by the Academy?", A: "The Oscar"},
	{Q: "What British rock band released the album Abbey Road?", A: "The Beatles"},
	{Q: "What is the name of the young lion prince in Disney's The Lion King?", A: "Simba"},
	{Q: "Who wrote the novel The Great Gatsby?", A: "F. Scott Fitzgerald"},
	{Q: "What is the term for traditional stories passed down orally through generations?", A: "Folklore"},
	{Q: "What ballet features the character of the Sugar Plum Fairy?", A: "The Nutcracker"},
	{Q: "Who composed The Nutcracker ballet?", A: "Pyotr Ilyich Tchaikovsky"},
	{Q: "What wooden puppet dreams of becoming a real boy in the classic story?", A: "Pinocchio"},
	{Q: "Who wrote the play Hamlet?", A: "William Shakespeare"},
	{Q: "What is the name of the famous mouse character created by Walt Disney?", A: "Mickey Mouse"},
	{Q: "What instrument does a drummer primarily play in a band?", A: "The drums"},
	{Q: "What genre of music originated in Jamaica and is associated with Bob Marley?", A: "Reggae"},
	{Q: "What art style, pioneered by Pablo Picasso, uses geometric shapes?", A: "Cubism"},
	{Q: "Who directed the movie Titanic (1997)?", A: "James Cameron"},
	{Q: "What is the name of the fictional archaeologist played by Harrison Ford in a famous film series?", A: "Indiana Jones"},
	{Q: "What is the name of the famous ballet about a princess turned into a swan?", A: "Swan Lake"},
	{Q: "Who wrote the play A Midsummer Night's Dream?", A: "William Shakespeare"},
	{Q: "How many players are on a standard soccer team on the field?", A: "Eleven"},
	{Q: "How many players are on a basketball team on the court at one time?", A: "Five"},
	{Q: "What sport is known as 'the beautiful game'?", A: "Football (soccer)"},
	{Q: "How often are the Summer Olympic Games held?", A: "Every four years"},
	{Q: "In tennis, what is a score of zero called?", A: "Love"},
	{Q: "What sport is played at Wimbledon?", A: "Tennis"},
	{Q: "How many holes are played in a standard round of golf?", A: "18"},
	{Q: "What sport uses a shuttlecock?", A: "Badminton"},
	{Q: "In baseball, how many players are on the field for one team?", A: "Nine"},
	{Q: "How many rings are on the Olympic flag?", A: "Five"},
	{Q: "What sport is associated with the Tour de France?", A: "Cycling"},
	{Q: "What country invented the sport of rugby?", A: "England"},
	{Q: "How many periods are in a standard game of ice hockey?", A: "Three"},
	{Q: "What is the term for a score of three under par on a single hole in golf?", A: "An albatross"},
	{Q: "What is the term for a score of one under par on a single hole in golf?", A: "A birdie"},
	{Q: "What is the maximum score possible in a single game of ten-pin bowling?", A: "300"},
	{Q: "What sport is played at the Kentucky Derby?", A: "Horse racing"},
	{Q: "How many players are on a volleyball team on the court?", A: "Six"},
	{Q: "What is the national sport of Japan?", A: "Sumo wrestling"},
	{Q: "What martial art originated in Brazil and focuses on ground grappling?", A: "Brazilian Jiu-Jitsu"},
	{Q: "What is the term for a hard hit that sends the ball straight down into the opponent's court in volleyball?", A: "A spike"},
	{Q: "How many points is a touchdown worth in American football?", A: "Six"},
	{Q: "What sport is played by the New York Yankees?", A: "Baseball"},
	{Q: "What sport is played by the Los Angeles Lakers?", A: "Basketball"},
	{Q: "What sport features events like the 100m dash and the marathon?", A: "Athletics (track and field)"},
	{Q: "What is the standard distance of a marathon in miles?", A: "26.2 miles"},
	{Q: "In which sport would you perform a slam dunk?", A: "Basketball"},
	{Q: "What is the term for a perfect score in gymnastics?", A: "A ten"},
	{Q: "What sport uses terms like 'love,' 'deuce,' and 'ace'?", A: "Tennis"},
	{Q: "How many players are on a standard cricket team?", A: "Eleven"},
	{Q: "What piece of equipment do you use to hit the ball in cricket and baseball?", A: "A bat"},
	{Q: "What winter sport involves sliding down an icy track on a sled?", A: "Bobsledding"},
	{Q: "What sport is associated with the term 'hat-trick'?", A: "Ice hockey"},
	{Q: "What country has won the most FIFA World Cups?", A: "Brazil"},
	{Q: "How often is the FIFA World Cup held?", A: "Every four years"},
	{Q: "What sport is played at the US Open, Wimbledon, French Open, and Australian Open?", A: "Tennis"},
	{Q: "What is the name for the area a soccer team must get the ball into to score?", A: "The goal"},
	{Q: "What is boxing categorized by, based on the fighters' body weight?", A: "Weight classes"},
	{Q: "What is the maximum number of clubs a golfer is allowed to carry in their bag?", A: "14"},
	{Q: "In American football, how many downs does a team get to advance ten yards?", A: "Four"},
	{Q: "What sport is played on a 'pitch' in the UK and often called 'football'?", A: "Soccer"},
	{Q: "What is the name of the trophy awarded to the winner of the NHL championship?", A: "The Stanley Cup"},
	{Q: "What sport does Serena Williams play?", A: "Tennis"},
	{Q: "What sport does Usain Bolt famously compete in?", A: "Sprinting"},
	{Q: "What sport does Michael Phelps famously compete in?", A: "Swimming"},
	{Q: "What sport is played in the Super Bowl?", A: "American football"},
	{Q: "What color jersey does the overall leader of the Tour de France wear?", A: "Yellow"},
	{Q: "What is it called when a golfer hits the ball into the hole with a single stroke?", A: "A hole in one"},
	{Q: "What sport features the positions of pitcher and catcher?", A: "Baseball"},
	{Q: "What Olympic sport involves routines performed on a balance beam, bars, and floor?", A: "Gymnastics"},
	{Q: "What is the main ingredient in guacamole?", A: "Avocado"},
	{Q: "What country is credited with inventing pizza as we know it?", A: "Italy"},
	{Q: "What grain is used to make bread?", A: "Wheat"},
	{Q: "What is the main ingredient in hummus?", A: "Chickpeas"},
	{Q: "What fruit is used to make wine?", A: "Grapes"},
	{Q: "What drink is made from fermented grapes?", A: "Wine"},
	{Q: "What is the main ingredient in traditional sushi?", A: "Rice"},
	{Q: "What spice is derived from the crocus flower and is the most expensive by weight?", A: "Saffron"},
	{Q: "What popular food is made by fermenting milk with live bacterial cultures?", A: "Yogurt"},
	{Q: "What vegetable is the main ingredient in French fries?", A: "Potatoes"},
	{Q: "What is the main ingredient in traditional Japanese miso soup?", A: "Fermented soybean paste"},
	{Q: "What nut is traditionally used to make pesto sauce along with basil?", A: "Pine nuts"},
	{Q: "What is the world's most consumed beverage after water?", A: "Tea"},
	{Q: "What country is generally credited as the origin of the croissant's popularity?", A: "France"},
	{Q: "What spice gives traditional Indian curry dishes their yellow color?", A: "Turmeric"},
	{Q: "What cheese is traditionally used on a Margherita pizza?", A: "Mozzarella"},
	{Q: "What ingredient gives traditional Caesar dressing its distinctive salty flavor?", A: "Anchovies"},
	{Q: "What is traditionally served with scones in a British cream tea?", A: "Clotted cream and jam"},
	{Q: "What is the main ingredient in chocolate?", A: "Cocoa beans"},
	{Q: "What drink is made by brewing roasted coffee beans?", A: "Coffee"},
	{Q: "What country is often credited with popularizing the hamburger?", A: "The United States"},
	{Q: "What is the main ingredient in traditional Italian risotto?", A: "Rice"},
	{Q: "What is the main ingredient in traditional French onion soup?", A: "Onions"},
	{Q: "What food family includes the ghost pepper and habanero, known for spiciness?", A: "Chili peppers"},
	{Q: "What is the main starchy ingredient in traditional Japanese ramen?", A: "Wheat noodles"},
	{Q: "What is the main ingredient in gazpacho, a cold Spanish soup?", A: "Tomatoes"},
	{Q: "What nut is the main ingredient in marzipan?", A: "Almonds"},
	{Q: "What is the main ingredient in the batter used to make traditional French crepes?", A: "Flour"},
	{Q: "What is a place where grapes are grown for winemaking called?", A: "A vineyard"},
	{Q: "What popular condiment is made primarily from tomatoes?", A: "Ketchup"},
	{Q: "What is the name of the thin, round Mexican flatbread made from corn or wheat?", A: "A tortilla"},
	{Q: "What fermented cabbage dish is a traditional Korean side dish?", A: "Kimchi"},
	{Q: "What legume is the main ingredient in traditional Middle Eastern falafel?", A: "Chickpeas"},
	{Q: "What is the world's most popular spice, derived from the Piper nigrum plant?", A: "Black pepper"},
	{Q: "What is the main sweetener extracted from sugar cane or sugar beets?", A: "Sugar"},
	{Q: "What spirit is traditionally used as the base of a Bloody Mary cocktail?", A: "Vodka"},
	{Q: "What is the main ingredient in a traditional omelet?", A: "Eggs"},
	{Q: "What Italian dessert's name translates to 'pick me up'?", A: "Tiramisu"},
	{Q: "What grain is most commonly used to brew beer?", A: "Barley"},
	{Q: "What fruit is used in a traditional British apple crumble?", A: "Apples"},
	{Q: "What language has the most native speakers worldwide?", A: "Mandarin Chinese"},
	{Q: "How many letters are in the English alphabet?", A: "26"},
	{Q: "What is the official language of Brazil?", A: "Portuguese"},
	{Q: "What is the official language of Mexico?", A: "Spanish"},
	{Q: "What language is primarily spoken in Egypt?", A: "Arabic"},
	{Q: "What alphabet is used to write the Russian language?", A: "The Cyrillic alphabet"},
	{Q: "What is the most widely spoken second language in the world?", A: "English"},
	{Q: "What ancient language is the basis for many modern European languages?", A: "Latin"},
	{Q: "What is the term for a word that reads the same forwards and backwards?", A: "A palindrome"},
	{Q: "What is the term for two words that sound the same but have different meanings, like 'flower' and 'flour'?", A: "Homophones"},
	{Q: "What punctuation mark is used to indicate a question?", A: "A question mark"},
	{Q: "What is often cited as one of the longest words in English, referring to a lung disease?", A: "Pneumonoultramicroscopicsilicovolcanoconiosis"},
	{Q: "What is the study of the origin of words called?", A: "Etymology"},
	{Q: "What is the term for a figure of speech comparing two things using 'like' or 'as'?", A: "A simile"},
	{Q: "What ancient writing system used pictures and symbols, common in ancient Egypt?", A: "Hieroglyphics"},
	{Q: "What is the official language of France?", A: "French"},
	{Q: "What is the official language of Germany?", A: "German"},
	{Q: "What is a word that means the opposite of another word called?", A: "An antonym"},
	{Q: "What is a word that means the same as another word called?", A: "A synonym"},
	{Q: "What broad language family does English belong to?", A: "Germanic"},
	{Q: "What is the term for a fictitious name used by an author instead of their real name?", A: "A pen name"},
	{Q: "What is the sign language used primarily in the United States called?", A: "American Sign Language"},
	{Q: "What is the name for the number symbols most commonly used worldwide today?", A: "Arabic numerals"},
	{Q: "What is the official language of most South American countries besides Brazil?", A: "Spanish"},
	{Q: "What do you call a group of words that doesn't form a complete sentence?", A: "A sentence fragment"},
	{Q: "What is the traditional greeting word used in Hawaii?", A: "Aloha"},
	{Q: "What is the term for a word borrowed from another language, like 'café' from French?", A: "A loanword"},
	{Q: "What is the international language used in air traffic control?", A: "English"},
	{Q: "What is the most commonly used letter in the English language?", A: "The letter E"},
	{Q: "What is the name of one of the two Japanese phonetic syllabaries used for writing?", A: "Hiragana"},
	{Q: "What is the smallest prime number?", A: "Two"},
	{Q: "How many sides does a triangle have?", A: "Three"},
	{Q: "How many sides does a hexagon have?", A: "Six"},
	{Q: "What is the value of pi rounded to two decimal places?", A: "3.14"},
	{Q: "What is the sum of the interior angles of a triangle?", A: "180 degrees"},
	{Q: "What is the square root of 64?", A: "Eight"},
	{Q: "How many degrees are in a right angle?", A: "90 degrees"},
	{Q: "What is 7 multiplied by 8?", A: "56"},
	{Q: "What is the term for a number that can only be divided evenly by 1 and itself?", A: "A prime number"},
	{Q: "How many sides does an octagon have?", A: "Eight"},
	{Q: "What is the term for a shape with four equal sides and four right angles?", A: "A square"},
	{Q: "What is the next number in the sequence 2, 4, 8, 16?", A: "32"},
	{Q: "How many degrees are in a full circle?", A: "360 degrees"},
	{Q: "What is the term for the longest side of a right triangle?", A: "The hypotenuse"},
	{Q: "What is 10 percent of 200?", A: "20"},
	{Q: "What is the Roman numeral for 50?", A: "L"},
	{Q: "What is the Roman numeral for 100?", A: "C"},
	{Q: "How many zeros are in one million?", A: "Six"},
	{Q: "What is the term for a number multiplied by itself?", A: "A squared number"},
	{Q: "What is the result of dividing any number by zero in standard math?", A: "Undefined"},
	{Q: "How many minutes are in a full day?", A: "1,440"},
	{Q: "What is the term for two lines that never intersect and stay the same distance apart?", A: "Parallel lines"},
	{Q: "What is the value of 5 factorial?", A: "120"},
	{Q: "How many sides does a pentagon have?", A: "Five"},
	{Q: "What is the term for a triangle with all three sides of equal length?", A: "Equilateral"},
	{Q: "What number comes after 999 in standard counting?", A: "1,000"},
	{Q: "What is 12 multiplied by 12?", A: "144"},
	{Q: "What is the term for the distance around a circle?", A: "The circumference"},
	{Q: "What is the average of 10, 20, and 30?", A: "20"},
	{Q: "How many even numbers are there between 1 and 10, inclusive?", A: "Five"},
	{Q: "What is the largest land animal on Earth?", A: "The African elephant"},
	{Q: "What is the fastest land animal?", A: "The cheetah"},
	{Q: "What is the tallest living land animal?", A: "The giraffe"},
	{Q: "What is the largest animal alive today?", A: "The blue whale"},
	{Q: "What animal is often called the 'King of the Jungle'?", A: "The lion"},
	{Q: "What is a baby kangaroo called?", A: "A joey"},
	{Q: "What is a baby dog called?", A: "A puppy"},
	{Q: "What is a baby cat called?", A: "A kitten"},
	{Q: "What is a group of lions called?", A: "A pride"},
	{Q: "What is a group of wolves called?", A: "A pack"},
	{Q: "What is a group of fish called?", A: "A school"},
	{Q: "What flightless bird is famous for its excellent swimming ability?", A: "The penguin"},
	{Q: "What is the only mammal capable of true flight?", A: "The bat"},
	{Q: "What is the largest species of big cat?", A: "The tiger"},
	{Q: "What reptile is famous for changing color to blend into its surroundings?", A: "The chameleon"},
	{Q: "What is the slowest-moving mammal in the world?", A: "The sloth"},
	{Q: "What insect is known for producing honey?", A: "The bee"},
	{Q: "What is a group of crows called?", A: "A murder"},
	{Q: "What sea creature has eight arms?", A: "The octopus"},
	{Q: "What is the tallest bird in the world?", A: "The ostrich"},
	{Q: "What bird has the largest wingspan of any living bird?", A: "The albatross"},
	{Q: "What animal is known for its black and white stripes?", A: "The zebra"},
	{Q: "What Australian marsupial carries its young in a pouch?", A: "The kangaroo"},
	{Q: "What is the national bird of the United States?", A: "The bald eagle"},
	{Q: "What is the fastest bird in the world during a hunting dive?", A: "The peregrine falcon"},
	{Q: "What is the largest species of shark?", A: "The whale shark"},
	{Q: "What continent has penguins living wild alongside a few other southern regions?", A: "Antarctica"},
	{Q: "What animal has the longest neck relative to its body?", A: "The giraffe"},
	{Q: "What is it called when a snake sheds its skin?", A: "Molting"},
	{Q: "What is the name for an adult male deer with antlers?", A: "A stag"},
	{Q: "What animal is known as man's best friend?", A: "The dog"},
	{Q: "What is the largest species of primate?", A: "The gorilla"},
	{Q: "What intelligent sea mammal is known for using echolocation?", A: "The dolphin"},
	{Q: "What is a baby cow called?", A: "A calf"},
	{Q: "What is a baby horse called?", A: "A foal"},
	{Q: "What bird is known for mimicking human speech?", A: "The parrot"},
	{Q: "What is the only country where kangaroos are found in the wild?", A: "Australia"},
	{Q: "What insect undergoes complete metamorphosis, changing from a caterpillar into this flying creature?", A: "A butterfly"},
	{Q: "What is the largest living rodent in the world?", A: "The capybara"},
	{Q: "What animal is known for building dams in rivers and streams?", A: "The beaver"},
	{Q: "What is the closest planet to the Sun?", A: "Mercury"},
	{Q: "What planet is known for its prominent rings?", A: "Saturn"},
	{Q: "What is the largest planet in our solar system?", A: "Jupiter"},
	{Q: "What is the smallest planet in our solar system?", A: "Mercury"},
	{Q: "How many planets are in our solar system?", A: "Eight"},
	{Q: "What planet is often called Earth's twin due to its similar size?", A: "Venus"},
	{Q: "What is the name of the galaxy that contains our solar system?", A: "The Milky Way"},
	{Q: "What is the term for a star that suddenly increases greatly in brightness before fading?", A: "A supernova"},
	{Q: "Who was the first human to travel into space?", A: "Yuri Gagarin"},
	{Q: "What was the name of the first artificial satellite launched into space?", A: "Sputnik 1"},
	{Q: "What space agency was responsible for the Apollo Moon missions?", A: "NASA"},
	{Q: "What is the name of NASA's famous space telescope launched in 1990?", A: "The Hubble Space Telescope"},
	{Q: "What planet has the most moons in our solar system?", A: "Saturn"},
	{Q: "What is the term for the point in an orbit where a planet is closest to the Sun?", A: "Perihelion"},
	{Q: "What force keeps planets in orbit around the Sun?", A: "Gravity"},
	{Q: "What is a large, rocky object orbiting the Sun that is too small to be a planet called?", A: "An asteroid"},
	{Q: "What is a small icy object that orbits the Sun and can form a glowing tail called?", A: "A comet"},
	{Q: "What is the term for the collapsed core of a massive star, with gravity so strong not even light escapes?", A: "A black hole"},
	{Q: "What dwarf planet used to be considered the ninth planet in our solar system?", A: "Pluto"},
	{Q: "What is the name of the space station currently orbiting Earth, involving multiple countries?", A: "The International Space Station"},
	{Q: "What is the name of Earth's only natural satellite?", A: "The Moon"},
	{Q: "What causes a solar eclipse?", A: "The Moon passing between the Earth and the Sun"},
	{Q: "What causes a lunar eclipse?", A: "The Earth passing between the Sun and the Moon"},
	{Q: "What is the term for a group of stars that forms a recognizable pattern?", A: "A constellation"},
	{Q: "What constellation is also known as the Great Bear?", A: "Ursa Major"},
	{Q: "What is the brightest star in the night sky, excluding the Sun?", A: "Sirius"},
	{Q: "What is the term for one complete orbit of the Earth around the Sun?", A: "A year"},
	{Q: "What planet is famous for the Great Red Spot, a giant storm?", A: "Jupiter"},
	{Q: "What is the name given to astronauts from Russia?", A: "Cosmonauts"},
	{Q: "What theory describes the origin of the universe from a single expanding point?", A: "The Big Bang theory"},
	{Q: "How many days are in a leap year?", A: "366"},
	{Q: "How many hours are in a day?", A: "24"},
	{Q: "How many days are in a standard week?", A: "Seven"},
	{Q: "What is the term for a period of ten years?", A: "A decade"},
	{Q: "What is the term for a period of 100 years?", A: "A century"},
	{Q: "What is the currency used in the United States?", A: "The dollar"},
	{Q: "What is the tallest man-made structure in the world?", A: "The Burj Khalifa"},
	{Q: "What color is a stop sign in most countries?", A: "Red"},
	{Q: "What side of the road do cars drive on in the United States?", A: "The right side"},
	{Q: "How many players are needed to play a standard game of chess?", A: "Two"},
	{Q: "How many squares are on a standard chessboard?", A: "64"},
	{Q: "What is the name for a baby's first set of teeth?", A: "Milk teeth"},
	{Q: "What is the term for the annual celebration of a person's birth date?", A: "A birthday"},
	{Q: "What metal is traditionally used to make a wedding ring in Western culture?", A: "Gold"},
	{Q: "How long does it take the Earth to rotate once on its axis?", A: "24 hours"},
	{Q: "What tool is used to tell direction, with a needle pointing north?", A: "A compass"},
	{Q: "What is the name for money given to a server for good service at a restaurant?", A: "A tip"},
	{Q: "How many minutes are in an hour?", A: "60"},
	{Q: "What is the standard legal voting age in the United States?", A: "18"},
	{Q: "What tool is used to measure temperature?", A: "A thermometer"},
}
